import getpass
import oracledb

# Prompt for password securely
pw = getpass.getpass("Enter password: ")

try:
    # Establish Thin-mode connection (no Oracle client required)
    connection = oracledb.connect(
        user="system",
        password=pw,
        dsn = "localhost/xepdb1"

    )
    print("Successfully connected to Oracle Database")
except oracledb.DatabaseError as e:
    print(f"Error connecting to Oracle: {e}")
    exit(1)



cursor = connection.cursor()

# --- Create table ---
cursor.execute("""
    CREATE TABLE students (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR2(100),
        major VARCHAR2(100),
        PRIMARY KEY (id)
    )
""")
print("Table created.")

# --- Insert Data ---
cursor.execute("""
    INSERT INTO students (name, major)
    VALUES ('Abhisek', 'Computer Science')
""")
connection.commit()
print("Data inserted.")

# --- Query Data ---
cursor.execute("SELECT * FROM students")
rows = cursor.fetchall()

print("Query result:")
for row in rows:
    print(row)

cursor.close()
connection.close()
